{{-- Field disusun satu kolom agar urut dari kiri ke bawah. --}}
<div class="container-fluid"><div class="row"><div class="col-md-12"><div class="row mx-1"><div class="card">
    <div class="card-header"><h5 class="mb-0">{{ $advance ? 'Edit' : 'Tambah' }} {{ $title_menu }}</h5></div><hr class="horizontal dark mt-0">
    <form action="{{ $action }}" method="POST"><div class="card-body">@csrf @if ($method !== 'POST') @method($method) @endif
        <div class="row form-satu-kolom">
            <div class="col-md-4"><div class="form-group"><label class="form-control-label">Nomor Form</label><input class="form-control" name="nomor_form" maxlength="50" required value="{{ old('nomor_form', $advance?->nomor_form) }}">@error('nomor_form')<p class="text-danger text-xs pt-1">{{ $message }}</p>@enderror</div></div>
            <div class="col-md-4"><div class="form-group"><label class="form-control-label">Tanggal</label><input class="form-control" type="date" name="tanggal" required value="{{ old('tanggal', $advance?->tanggal ?? now()->toDateString()) }}"></div></div>
            <div class="col-md-4"><div class="form-group"><label class="form-control-label">Nomor Faktur Pemasok</label><input class="form-control" name="nomor_faktur_pemasok" maxlength="50" required value="{{ old('nomor_faktur_pemasok', $advance?->nomor_faktur_pemasok) }}"></div></div>
            <div class="col-md-6"><div class="form-group"><label class="form-control-label">Pemasok</label><select class="form-select" name="pemasok_id" required><option value=""></option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}" @selected(old('pemasok_id', $advance?->pemasok_id) == $supplier->id)>{{ $supplier->kode_pemasok }} - {{ $supplier->nama }}</option>@endforeach</select></div></div>
            <div class="col-md-6"><div class="form-group"><label class="form-control-label">Pesanan Pembelian</label><select class="form-select" name="pesanan_pembelian_id"><option value=""></option>@foreach($orders as $order)<option value="{{ $order->id }}" @selected(old('pesanan_pembelian_id', $advance?->pesanan_pembelian_id) == $order->id)>{{ $order->nomor }} - {{ $order->nama_pemasok_snapshot }}</option>@endforeach</select></div></div>
            <div class="col-md-4"><div class="form-group"><label class="form-control-label">Mata Uang</label><select class="form-select" name="mata_uang_id"><option value=""></option>@foreach($currencies as $currency)<option value="{{ $currency->id }}" @selected(old('mata_uang_id', $advance?->mata_uang_id) == $currency->id)>{{ $currency->kode }}</option>@endforeach</select></div></div>
            <div class="col-md-4"><div class="form-group"><label class="form-control-label">Syarat Pembayaran</label><select class="form-select" name="syarat_pembayaran_id"><option value=""></option>@foreach($terms as $term)<option value="{{ $term->id }}" @selected(old('syarat_pembayaran_id', $advance?->syarat_pembayaran_id) == $term->id)>{{ $term->nama }}</option>@endforeach</select></div></div>
            <div class="col-md-4"><div class="form-group"><label class="form-control-label">Bank Pemasok</label><select class="form-select" name="rekening_bank_pemasok_id"><option value=""></option>@foreach($banks as $bank)<option value="{{ $bank->id }}" @selected(old('rekening_bank_pemasok_id', $advance?->rekening_bank_pemasok_id) == $bank->id)>{{ $bank->nama_bank }} - {{ $bank->nomor_rekening }}</option>@endforeach</select></div></div>
            <div class="col-md-4"><div class="form-group"><label class="form-control-label">Jumlah Uang Muka</label><input class="form-control" type="number" min="0.01" step="0.01" name="jumlah_uang_muka" required value="{{ old('jumlah_uang_muka', $advance?->jumlah_uang_muka) }}"></div></div>
            <div class="col-md-4"><div class="form-group"><label class="form-control-label">Jumlah Pajak</label><input class="form-control" type="number" min="0" step="0.01" name="jumlah_pajak" value="{{ old('jumlah_pajak', $advance?->jumlah_pajak) }}"></div></div>
            <div class="col-md-2"><div class="form-check"><input class="form-check-input" type="checkbox" name="kena_pajak" value="1" @checked(old('kena_pajak', $advance?->kena_pajak))><label class="form-check-label">Kena Pajak</label></div></div>
            <div class="col-md-2"><div class="form-check"><input class="form-check-input" type="checkbox" name="total_termasuk_pajak" value="1" @checked(old('total_termasuk_pajak', $advance?->total_termasuk_pajak))><label class="form-check-label">Termasuk Pajak</label></div></div>
            <div class="col-md-6"><div class="form-group"><label class="form-control-label">Alamat</label><textarea class="form-control" name="alamat">{{ old('alamat', $advance?->alamat) }}</textarea></div></div>
            <div class="col-md-6"><div class="form-group"><label class="form-control-label">Keterangan</label><textarea class="form-control" name="keterangan">{{ old('keterangan', $advance?->keterangan) }}</textarea></div></div>
        </div>
    </div><div class="card-footer"><button class="btn btn-primary mb-0" type="submit"><i class="fas fa-save me-1"></i>Simpan</button><button class="btn btn-secondary mb-0" type="button" onclick="window.location='{{ url($url_menu) }}'">Kembali</button></div></form>
</div></div></div></div></div>
