@extends('layouts.app', ['class' => 'g-sidenav-show bg-gray-100'])
{{-- Tabel memakai inisialisasi DataTables dari layout framework. --}}
@section('content')
    @include('layouts.navbars.auth.topnav', ['title' => ''])
    <div class="container-fluid"><div class="row"><div class="col-md-12"><div class="row mx-1"><div class="card">
        <div class="row"><div class="card-header col-md-auto"><h5 class="mb-0">List {{ $title_menu }}</h5></div><div class="col">@include('components.alert')</div></div><hr class="horizontal dark mt-0">
        <div class="row px-4 py-2"><div class="col-lg">@if ($authorize->add == '1')<button class="btn btn-primary mb-0" onclick="window.location='{{ url($url_menu . '/add') }}'"><i class="fas fa-plus me-1"></i><span class="font-weight-bold">Tambah</span></button>@endif</div></div>
        <div class="row px-4 py-2"><div class="table-responsive"><table class="table display" id="list_{{ $dmenu }}"><thead class="thead-light" style="background-color: #00b7bd4f;"><tr><th width="110">Action</th><th>No</th><th>Nomor</th><th>Tanggal</th><th>Pemasok</th><th>Pesanan</th><th>Total</th><th>Status</th></tr></thead><tbody>
        @foreach ($advances as $advance)<tr {{ $advance->status === 'dibatalkan' ? 'style=background-color:#ffe9ed;' : '' }}><td class="text-sm font-weight-normal"><div class="btn-group"><button class="btn btn-primary btn-sm mb-0 px-3" type="button" onclick="window.location='{{ url($url_menu . '/show/' . encrypt($advance->id)) }}'"><i class="fas fa-eye"></i><span class="font-weight-bold"> View</span></button><button type="button" class="btn btn-sm btn-primary mb-0 px-3 dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown"><span class="visually-hidden">Toggle Dropdown</span></button><ul class="dropdown-menu">@if ($authorize->edit == '1' && $advance->status === 'draf')<li><button type="button" class="btn btn-sm btn-warning mx-2 mb-0 w-90" onclick="window.location='{{ url($url_menu . '/edit/' . encrypt($advance->id)) }}'"><i class="fas fa-edit"></i><span class="font-weight-bold"> Edit</span></button></li>@endif @if ($authorize->delete == '1' && $advance->status === 'draf')<li><hr class="dropdown-divider"></li><li><form action="{{ url($url_menu . '/' . encrypt($advance->id)) }}" method="POST">@csrf @method('DELETE')<button class="btn btn-sm btn-danger mx-2 mb-0 w-90" onclick="return confirm('Batalkan uang muka ini?')"><i class="fas fa-ban"></i><span class="font-weight-bold"> Batalkan</span></button></form></li>@endif</ul></div></td><td>{{ $loop->iteration }}</td><td class="text-sm font-weight-bold text-dark">{{ $advance->nomor_form }}</td><td class="text-sm">{{ $advance->tanggal }}</td><td class="text-sm">{{ $advance->pemasok }}</td><td class="text-sm">{{ $advance->nomor_pesanan }}</td><td class="text-sm">{{ number_format($advance->total_akhir, 2, ',', '.') }}</td><td class="text-sm">{{ ucfirst($advance->status) }}</td></tr>@endforeach
        </tbody></table></div></div><div class="row px-4 py-2"><div class="col-lg"><div class="nav-wrapper"><code>Note : <i aria-hidden="true" style="color: #ffc2cd;" class="fas fa-circle"></i> Dokumen dibatalkan</code></div></div></div>
    </div></div></div></div></div>
@endsection
