<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        // Drop existing table (schema changed)
        Schema::dropIfExists('barang_jasa');

        Schema::create('barang_jasa', function (Blueprint $table) {
            // Primary key — auto-generated by framework (BRG00001, etc.)
            $table->string('kode_barang', 50)->primary();

            // Required fields
            $table->string('nama_barang', 150);
            $table->enum('kategori_barang', ['umum', 'jasa']);
            $table->enum('jenis_barang', ['prsd', 'non_prsd', 'jasa', 'grup']);

            // Optional fields
            $table->string('upc_barcode', 50)->nullable();
            $table->enum('satuan', ['Jam', 'Liter', 'KG', 'PCS']);
            $table->string('merk_barang', 100)->nullable();

            // Framework standard columns
            $table->enum('isactive', ['0', '1'])->default('1');
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent()->useCurrentOnUpdate();
            $table->string('user_create')->nullable();
            $table->string('user_update')->nullable();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('barang_jasa');
    }
};
